"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app

CTLE: this script is used to generate a standalone application (for Mac OS)
done by terminal command:
$ python2.7 setup.py py2app
"""

from setuptools import setup

APP = ['MONGOOSEgui.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
